In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
train = pd.read_csv('/content/train.csv')
test = pd.read_csv("test.csv")

In [52]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

# Logistics regrassion

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib

# Initialize the StandardScaler
scaler = StandardScaler()

# Prepare features and target
X = train.drop("price_range", axis=1)
y = train["price_range"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Scale the features
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize and train the Logistic Regression model
svc_model = SVC()
svc_model.fit(X_train_scaled, y_train)

# Make predictions on the scaled test set
pred1 = svc_model.predict(X_test_scaled)

# Evaluate the model using appropriate classification metrics

accuracy1 = accuracy_score(y_test, pred1)
print("Accuracy:", accuracy1)
print("Classification Report:\n", classification_report(y_test, pred1))
print("Confusion Matrix:\n", confusion_matrix(y_test, pred1))

Accuracy: 0.895
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.94      0.95       100
           1       0.87      0.87      0.87       100
           2       0.82      0.87      0.84       100
           3       0.94      0.90      0.92       100

    accuracy                           0.90       400
   macro avg       0.90      0.90      0.90       400
weighted avg       0.90      0.90      0.90       400

Confusion Matrix:
 [[94  6  0  0]
 [ 4 87  9  0]
 [ 0  7 87  6]
 [ 0  0 10 90]]


In [61]:
joblib.dump(svc_model, 'SVC.joblib')

['SVC.joblib']

In [54]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score

In [58]:
models = {
    'Logistic Regression' : LogisticRegression(max_iter=1000, solver='liblinear', random_state=42),
    'DecisionTreeClassifier': DecisionTreeClassifier(random_state=42),
    'naive_bayes' : GaussianNB(),
    'KNeighborsClassifier' : KNeighborsClassifier(),
    'SVM' : SVC(probability=True, random_state=42)
}

result = []

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted') # Corrected y_pred and added average parameter
    result.append({
        'model': name,
        'Accuracy': acc,
        'F1-Score': f1 # Added F1-Score to results
    })

# Print results for better visibility
for res in result:
    print(f"Model: {res['model']}, Accuracy: {res['Accuracy']:.4f}, F1-Score: {res['F1-Score']:.4f}")

Model: Logistic Regression, Accuracy: 0.8600, F1-Score: 0.8549
Model: DecisionTreeClassifier, Accuracy: 0.8200, F1-Score: 0.8210
Model: naive_bayes, Accuracy: 0.8550, F1-Score: 0.8554
Model: KNeighborsClassifier, Accuracy: 0.4900, F1-Score: 0.4831
Model: SVM, Accuracy: 0.8950, F1-Score: 0.8954
